### ISSUE TITLE
stack-overflow in re_match_regexp

### ISSUE THREAD

**Issue by renatahodovan** [pando-project/jerryscript#2190]
###### Jerry version:

```
Checked revision: 918eb22a
Build command: ./tools/build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --compile-flag=-g --jerry-libc=off --static-link=off --strip=off --system-allocator=on --linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```
###### OS:

```
Ubuntu 17.10
```
###### Test case:

```javascript
/(?:(?=x)){1000}xyz/.exec('xyz'); 
```

Usually, I do not report stack-overflows since they are due to recursive js calls mostly.
However, in this case the failure disappears if I remove either the positive lookahed or the non-capturing brackets.
So I leave to the experts to decide whether this is a feature or a bug.

###### Backtrace:

```
ASAN:DEADLYSIGNAL
=================================================================
==24793==ERROR: AddressSanitizer: stack-overflow on address 0xff0acfe8 (pc 0x080cead4 bp 0xff0ad448 sp 0xff0acfec T0)
    #0 0x80cead3 in __interceptor_memcpy.part.43 (jerryscript/build/bin/jerry+0x80cead3)
    #1 0x834eda7 in re_get_value jerryscript/jerry-core/parser/regexp/re-bytecode.c:157:3
    #2 0x82fb7a5 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:947:19
    #3 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #4 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #5 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #6 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #7 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #8 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #9 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #10 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #11 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #12 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #13 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #14 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #15 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #16 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #17 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #18 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #19 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #20 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #21 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #22 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #23 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #24 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #25 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #26 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #27 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #28 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #29 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #30 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #31 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #32 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #33 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #34 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #35 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #36 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #37 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #38 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #39 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #40 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #41 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #42 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #43 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #44 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #45 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #46 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #47 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #48 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #49 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #50 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #51 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #52 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #53 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #54 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #55 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #56 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #57 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #58 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #59 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #60 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #61 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #62 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #63 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #64 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #65 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #66 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #67 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #68 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #69 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #70 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #71 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #72 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #73 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #74 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #75 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #76 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #77 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #78 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #79 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #80 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #81 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #82 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #83 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #84 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #85 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #86 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #87 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #88 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #89 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #90 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #91 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #92 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #93 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #94 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #95 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #96 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #97 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #98 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #99 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #100 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #101 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #102 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #103 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #104 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #105 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #106 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #107 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #108 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #109 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #110 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #111 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #112 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #113 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #114 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #115 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #116 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #117 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #118 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #119 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #120 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #121 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #122 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #123 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #124 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #125 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #126 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #127 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #128 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #129 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #130 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #131 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #132 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #133 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #134 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #135 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #136 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #137 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #138 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #139 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #140 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #141 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #142 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #143 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #144 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #145 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #146 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #147 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #148 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #149 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #150 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #151 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #152 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #153 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #154 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #155 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #156 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #157 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #158 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #159 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #160 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #161 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #162 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #163 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #164 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #165 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #166 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #167 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #168 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #169 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #170 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #171 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #172 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #173 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #174 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #175 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #176 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #177 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #178 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #179 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #180 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #181 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #182 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #183 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #184 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #185 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #186 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #187 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #188 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #189 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #190 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #191 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #192 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #193 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #194 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #195 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #196 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #197 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #198 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #199 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #200 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #201 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #202 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #203 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #204 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #205 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #206 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #207 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #208 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #209 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #210 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #211 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #212 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #213 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #214 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #215 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #216 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #217 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #218 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #219 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #220 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #221 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #222 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #223 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #224 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #225 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #226 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #227 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #228 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #229 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #230 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #231 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #232 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #233 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #234 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #235 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #236 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #237 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #238 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #239 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #240 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #241 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #242 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #243 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #244 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #245 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38
    #246 0x82fc69e in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:987:38
    #247 0x82fd375 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:1032:38
    #248 0x82f5e53 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:565:27
    #249 0x82f9fc1 in re_match_regexp jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:840:38

SUMMARY: AddressSanitizer: stack-overflow (jerryscript/build/bin/jerry+0x80cead3) in __interceptor_memcpy.part.43
==24793==ABORTING

```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by LaszloLango** [comment]
I cannot reproduce this issue.

**Comment by renatahodovan** [comment]
It seems that it's only reproducible with a clang build:

CC=clang ./tools/build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --compile-flag=-g --jerry-libc=off --static-link=off --strip=off --system-allocator=on --linker-flag=-fuse-ld=gold --lto=off --profile=es2015-subset --error-messages=on
