### ISSUE TITLE
Assertion 'ecma_is_value_undefined (value) || ecma_is_value_null (value) || ecma_is_value_boolean (value) || ecma_is_value_number (value) || ecma_is_value_string (value) || ecma_is_value_object (value)' failed in ecma_check_value_type_is_spec_defined

### ISSUE THREAD

**Issue by renatahodovan** [pando-project/jerryscript#2654]
###### Jerry version:

```
Checked revision: ec142f5f
Build command: ./tools/build.py --clean --debug --profile=es2015-subset --logging=on
```

###### OS:

```
Ubuntu 18.04, x86_64
```

###### Test case:

```javascript
--null.static ? this : [ , ] instanceof true; 
```

###### Backtrace:

```
ICE: Assertion 'ecma_is_value_undefined (value) || ecma_is_value_null (value) || ecma_is_value_boolean (value) || ecma_is_value_number (value) || ecma_is_value_string (value) || ecma_is_value_object (value)' failed at jerryscript/jerry-core/ecma/base/ecma-helpers-value.c(ecma_check_value_type_is_spec_defined):386.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7a24801 in __GI_abort () at abort.c:79
#2  0x000055555555f2f6 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:71
#3  0x000055555558b684 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:63
#4  0x000055555558b6d6 in jerry_assert_fail (
    assertion=0x5555555e3c78 "ecma_is_value_undefined (value) || ecma_is_value_null (value) || ecma_is_value_boolean (value) || ecma_is_value_number (value) || ecma_is_value_string (value) || ecma_is_value_object (value)", file=0x5555555e3c28 "jerryscript/jerry-core/ecma/base/ecma-helpers-value.c", 
    function=0x5555555d0ac0 <__func__.3728.lto_priv.660> "ecma_check_value_type_is_spec_defined", line=386) at jerryscript/jerry-core/jrt/jrt-fatals.c:87
#5  0x00005555555b0570 in ecma_check_value_type_is_spec_defined (value=24) at jerryscript/jerry-core/ecma/base/ecma-helpers-value.c:381
#6  0x000055555559dd8c in ecma_op_to_number (value=24) at jerryscript/jerry-core/ecma/operations/ecma-conversion.c:244
#7  0x00005555555988a3 in vm_loop (frame_ctx_p=0x7fffffffdc00) at jerryscript/jerry-core/vm/vm.c:1819
#8  0x000055555559bcfe in vm_execute (frame_ctx_p=0x7fffffffdc00, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3428
#9  0x000055555559bfd7 in vm_run (bytecode_header_p=0x5555558f75c0 <jerry_global_heap+512>, this_binding_value=27, lex_env_p=0x5555558f73f0 <jerry_global_heap+48>, parse_opts=0, arg_list_p=0x0, 
    arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3531
#10 0x00005555555958f6 in vm_run_global (bytecode_p=0x5555558f75c0 <jerry_global_heap+512>) at jerryscript/jerry-core/vm/vm.c:227
#11 0x00005555555c2595 in jerry_run (func_val=203) at jerryscript/jerry-core/api/jerry.c:544
#12 0x00005555555c0ea0 in main (argc=3, argv=0x7fffffffe038) at jerryscript/jerry-main/main-unix.c:676
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by rerobika** [comment]
This issue is the side effect of #2607. I'm going to fix it.
