### ISSUE TITLE
Assertion 'frame_ctx_p->registers_p + register_end + frame_ctx_p->context_depth == stack_top_p' failed at jerryscript//jerry-core/vm/vm.c(vm_loop):1343

### ISSUE THREAD

**Issue by havrikov** [pando-project/jerryscript#2819]
### Version
Revision: 40f7b1c2  

Build command: `./tools/build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --compile-flag=-g --strip=off --system-allocator=off --logging=on --linker-flag=-fuse-ld=gold --linker-flag=-fsanitize=address --linker-flag=-static-libasan --error-messages=on --profile=es2015-subset`  

Operating system: `Linux-4.9.0-8-amd64-x86_64-with-debian-9.8`

## Input 
```js
for ( this << class  extends  this {} in  this ){}
```
### Backtrace 
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6f2a42a in __GI_abort () at abort.c:89
#2  0x0000555555599f9d in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript//jerry-port/default/default-fatal.c:71
#3  0x0000555555620b21 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript//jerry-core/jrt/jrt-fatals.c:58
#4  0x0000555555620b78 in jerry_assert_fail (assertion=0x5555557943a0 "frame_ctx_p->registers_p + register_end + frame_ctx_p->context_depth == stack_top_p", file=0x555555793fe0 "jerryscript//jerry-core/vm/vm.c", function=0x5555557644c0 <__func__.6033.lto_priv.453> "vm_loop", line=1343) at jerryscript//jerry-core/jrt/jrt-fatals.c:82
#5  0x00005555555fe39b in vm_loop.lto_priv.450 (frame_ctx_p=0x7fffffffd8f0) at jerryscript//jerry-core/vm/vm.c:1343
#6  0x00005555555f820a in vm_execute (frame_ctx_p=0x7fffffffd8f0, arg_p=0x0, arg_list_len=0) at jerryscript//jerry-core/vm/vm.c:3477
#7  0x00005555555f88ae in vm_run (bytecode_header_p=0x5555559063e0 <jerry_global_heap+512>, this_binding_value=27, lex_env_p=0x555555906210 <jerry_global_heap+48>, parse_opts=0, arg_list_p=0x0, arg_list_len=0) at jerryscript//jerry-core/vm/vm.c:3595
#8  0x000055555560e29e in vm_run_global (bytecode_p=0x5555559063e0 <jerry_global_heap+512>) at jerryscript//jerry-core/vm/vm.c:273
#9  0x000055555567ace7 in jerry_run (func_val=203) at jerryscript//jerry-core/api/jerry.c:549
#10 0x000055555567e7cf in main (argc=3, argv=0x7fffffffde08) at jerryscript//jerry-main/main-unix.c:742
```

**Comment by akosthekiss** [comment]
Confirmed on latest master (e944cdaa) and on macOS with simpler build configuration:

```
$ build/bin/jerry --version
Version: 1.0 (e944cdaa)
$ build/bin/jerry issue-2819.js 
ICE: Assertion 'frame_ctx_p->registers_p + register_end + frame_ctx_p->context_depth == stack_top_p' failed at /Users/akiss/devel/jerry/jerryscript/jerry-core/vm/vm.c(vm_loop):1343.
Error: ERR_FAILED_INTERNAL_ASSERTION
$ python -c 'import platform; print(platform.platform())'
Darwin-18.5.0-x86_64-i386-64bit

```
