### ISSUE TITLE
Assertion 'ecma_find_named_property (object_p, name_p) == NULL' failed in ecma_create_named_data_property

### ISSUE THREAD

**Issue by renatahodovan** [pando-project/jerryscript#2824]
###### Jerry version:

```
Checked revision: e944cdaa

Build command: ./tools/build.py --clean --debug --compile-flag=-m32 --profile=es2015-subset --system-allocator=on --error-messages=on --logging=on
```

###### OS:

```
Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```js
var $ = Function("import { c } from 'tests/jerry/es2015/module-imported.js';")
var c
```

###### Backtrace:

```
ICE: Assertion 'ecma_find_named_property (object_p, name_p) == NULL' failed at jerryscript/jerry-core/ecma/base/ecma-helpers.c(ecma_create_named_data_property):535.
Error: ERR_FAILED_INTERNAL_ASSERTION

bt
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf7de0832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7de1cc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5655c852 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x565a0518 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x565a0552 in jerry_assert_fail (assertion=0x565e83c8 "ecma_find_named_property (object_p, name_p) == NULL", file=0x565e7ffc "jerryscript/jerry-core/ecma/base/ecma-helpers.c", function=0x565d0940 <__func__.4933.lto_priv.668> "ecma_create_named_data_property", line=535) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x565c7bf3 in ecma_create_named_data_property (object_p=0x566fa180, name_p=0x566fa6a0, prop_attributes=0 '\000', out_prop_p=0xffffca48) at jerryscript/jerry-core/ecma/base/ecma-helpers.c:535
#7  0x56593423 in ecma_module_connect_properties (scope_p=0x566fab70) at jerryscript/jerry-core/ecma/base/ecma-module.c:143
#8  0x5659360a in ecma_parser_module_run (file_path_p=0x566fa6c0 "tests/jerry/es2015/module-imported.js", path_size=38, source_p=0x566fb720 "/* Copyright JS Foundation and other contributors, http://js.foundation\n *\n * Licensed under the Apache License, Version 2.0 (the \"License\");\n * you may not use this file except in compliance with the"..., source_size=793, module_node_p=0x566fa6f0) at jerryscript/jerry-core/ecma/base/ecma-module.c:213
#9  0x565936ab in ecma_module_load_modules (context_p=0xffffcb5c) at jerryscript/jerry-core/ecma/base/ecma-module.c:241
#10 0x56588f00 in parser_parse_source (arg_list_p=0x565e5b34 "", arg_list_size=0, source_p=0x566fa518 "import { c } from 'tests/jerry/es2015/module-imported.js';", source_size=58, parse_opts=0, error_location_p=0xffffccd8) at jerryscript/jerry-core/parser/js/js-parser.c:2486
#11 0x56589936 in parser_parse_script (arg_list_p=0x565e5b34 "", arg_list_size=0, source_p=0x566fa518 "import { c } from 'tests/jerry/es2015/module-imported.js';", source_size=58, parse_opts=0, bytecode_data_p=0xffffcd3c) at jerryscript/jerry-core/parser/js/js-parser.c:2937
#12 0x56578c18 in ecma_builtin_function_dispatch_construct (arguments_list_p=0xffffcf44, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-function.c:168
#13 0x5657895d in ecma_builtin_function_dispatch_call (arguments_list_p=0xffffcf44, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-function.c:59
#14 0x565a54bd in ecma_builtin_dispatch_call (obj_p=0x566fa660, this_arg_value=72, arguments_list_p=0xffffcf44, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1051
#15 0x565adbcb in ecma_op_function_call (func_obj_p=0x566fa660, this_arg_value=72, arguments_list_p=0xffffcf44, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:715
#16 0x5658d3a5 in opfunc_call (frame_ctx_p=0xffffcf5c) at jerryscript/jerry-core/vm/vm.c:572
#17 0x56592df9 in vm_execute (frame_ctx_p=0xffffcf5c, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3483
#18 0x56592ffc in vm_run (bytecode_header_p=0x566fa560, this_binding_value=1450156419, lex_env_p=0x566fa1b0, parse_opts=0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3595
#19 0x5658ce48 in vm_run_global (bytecode_p=0x566fa560) at jerryscript/jerry-core/vm/vm.c:273
#20 0x565b4eb4 in jerry_run (func_val=1450157603) at jerryscript/jerry-core/api/jerry.c:549
#21 0x565b3847 in main (argc=3, argv=0xffffd204) at jerryscript/jerry-main/main-unix.c:742
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by rerobika** [comment]
Closing the issue since it has been fixed via #2792.
